COUNTRIES = {
  "UNITED STATES": "United States of America",
  "China - Taiwan": "Taiwan",
  "China - Hong Kong SAR": "Hong Kong",
  "Korea (Republic of)": "South Korea",
  "Belgium - Flemish Community": "Belgium",
  "Belgium - French Community": "Belgium",
  "MACAU": "Macao",
  "China - Macao SAR": "Macao",
  "Venezuela (Bolivarian Republic of)": "Venezuela",
  "TRINIDAD": "Trinidad and Tobago",
  "Lao People's Democratic Republic": "Laos",
  "Iran (Islamic Republic of)": "Iran",
  "MARTINIQUE": "France",
  "France - Martinique": "France",
  "France - Reunion": "France",
  "France - French Polynesia": "France",
  "KOREA, REPUBLIC OF": "South Korea",
  "Korea (Democratic People's Republic of)": "North Korea",
  "Congo (Democratic Republic)": "Congo",
  "Bolivia (Plurinational State of)": "Bolivia",
  "Macedonia (The Former Yugoslav Republic)": "Macedonia",
  "Switezrland": "Switzerland"
}
